name: Update Dockerfiles and docker-compose files

on: [push]
#  release:
#    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v1
      - name: Make Dockerfiles
        run: make dockerfiles
      - name: Commit back to repository
        run: |
          git add dockerfiles/*  compose/*
          git commit -m "Update Dockerfiles and docker-compose files" || echo "No changes to commit"
          git push origin ${GITHUB_REF##*/} || echo "No changes to commit"
