name: Update container definition files

on:
  schedule:
    - cron: "0 10 * * *"
  workflow_dispatch:

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    container:
      image: rocker/tidyverse:latest
    steps:
      - uses: actions/checkout@v4
      - name: Set as safe for following git commands
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: install packages
        run: |
          install2.r --error --skipinstalled -n -1 pak
      - name: Make changes to pull request
        run: |
          ./build/make-stacks.R
          make clean
          make setup
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Automatic update of container definition files
          author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          signoff: false
          branch: auto-detected-updates
          delete-branch: true
          title: 'Automatic update of container definition files'
          body: |
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          draft: false
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
