name: Build & Push extensions 

on: [push]
#  release:
#    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
      - name: Build the tagged Docker image
        run: | 
             docker-compose -f compose/extensions-3.6.3.yml build 
             docker-compose -f compose-rockerdev/extensions-3.6.3.yml build 
      - name: Push the tagged Docker image
        run: docker-compose  -f compose-rockerdev/extensions-3.6.3.yml push


