name: Create new release
on:
  push:
    branches:
      - "master"
    paths:
      - "build/matrix/latest.json"
  workflow_dispatch:

jobs:
  create_tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag-version.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v5

      - id: set-version
        run: |
          NEW_VERSION="$(jq '.r_version[-1]' -r build/matrix/latest.json)"
          echo "newversion=${NEW_VERSION}" >>"$GITHUB_OUTPUT"
          echo "${NEW_VERSION}"

      - name: Bump version and push tag
        id: tag-version
        uses: mathieudutour/github-tag-action@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: false
          custom_tag: ${{ steps.set-version.outputs.newversion }}
          tag_prefix: "R"

  create_release:
    needs: create_tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.create_tag.outputs.tag }}
          generateReleaseNotes: true
          allowUpdates: false
          token: ${{ secrets.GITHUB_TOKEN }}
